services:
  bd:
    image: postgres:latest
    environment:
      POSTGRES_DB: "dbForWorkTgBot"
      POSTGRES_USER: ${dbUserName}
      POSTGRES_PASSWORD: ${dbPassword}
    ports:
      - "9000:5432"